// Levantine Arabic (شامي) learning data.
// Transliteration: ḥ ṭ ṣ ḍ ʿ ʾ, long vowels ā ē ī ō ū.
// `wik` overrides the Wiktionary page title when it differs from `ar`.

const VOCAB = [
  // ——— Greetings & politeness ———
  { ar: "مرحبا", tr: "marḥaba", en: "hi, hello", cat: "Greetings" },
  { ar: "أهلين", tr: "ahlēn", en: "hi! (warm reply to marḥaba)", cat: "Greetings", wik: "اهلين" },
  { ar: "صباح الخير", tr: "ṣabāḥ il-khēr", en: "good morning", cat: "Greetings", wik: "صباح الخير" },
  { ar: "مسا الخير", tr: "masa l-khēr", en: "good evening", cat: "Greetings", wik: "مسا الخير" },
  { ar: "كيفك؟", tr: "kīfak? / kīfik?", en: "how are you? (m/f)", cat: "Greetings", wik: "كيفك" },
  { ar: "منيح", tr: "mnīḥ", en: "good, fine, well (f: mnīḥa)", cat: "Greetings" },
  { ar: "تمام", tr: "tamām", en: "fine, perfect, OK", cat: "Greetings" },
  { ar: "الحمد لله", tr: "il-ḥamdilla", en: "thank God; (I'm) fine", cat: "Greetings", wik: "الحمد لله" },
  { ar: "شكراً", tr: "shukran", en: "thank you", cat: "Greetings", wik: "شكرا" },
  { ar: "تكرم", tr: "tikram", en: "you're welcome; at your service", cat: "Greetings" },
  { ar: "لو سمحت", tr: "law samaḥt", en: "please; excuse me", cat: "Greetings", wik: "لو سمحت" },
  { ar: "عن إذنك", tr: "ʿan iznak", en: "excuse me (when leaving)", cat: "Greetings", wik: "عن اذنك" },
  { ar: "يعطيك العافية", tr: "yaʿṭīk il-ʿāfye", en: "well done / thanks (to s.o. working)", cat: "Greetings", wik: "يعطيك العافية" },
  { ar: "مع السلامة", tr: "maʿ is-salāme", en: "goodbye", cat: "Greetings", wik: "مع السلامة" },
  { ar: "إن شاء الله", tr: "inshaḷḷa", en: "hopefully, God willing", cat: "Greetings", wik: "ان شاء الله" },
  { ar: "يلا", tr: "yaḷḷa", en: "come on!, let's go!", cat: "Greetings" },
  { ar: "معليش", tr: "maʿlēsh", en: "never mind, it's OK, sorry", cat: "Greetings" },
  { ar: "مبروك", tr: "mabrūk", en: "congratulations!", cat: "Greetings" },
  { ar: "أهلا وسهلا", tr: "ahla w sahla", en: "welcome!", cat: "Greetings", wik: "اهلا وسهلا" },
  { ar: "تشرفنا", tr: "tsharrafna", en: "nice to meet you", cat: "Greetings" },

  // ——— Question words ———
  { ar: "شو", tr: "shū", en: "what?", cat: "Questions" },
  { ar: "ليش", tr: "lēsh", en: "why?", cat: "Questions" },
  { ar: "وين", tr: "wēn", en: "where?", cat: "Questions" },
  { ar: "إيمتى", tr: "ēmta", en: "when?", cat: "Questions", wik: "ايمتى" },
  { ar: "كيف", tr: "kīf", en: "how?", cat: "Questions" },
  { ar: "مين", tr: "mīn", en: "who?", cat: "Questions" },
  { ar: "قديش", tr: "addēsh", en: "how much?, how many?", cat: "Questions" },
  { ar: "أي", tr: "ayya", en: "which?", cat: "Questions", wik: "اي" },
  { ar: "شو في؟", tr: "shū fī?", en: "what's up?, what's going on?", cat: "Questions", wik: "شو في" },

  // ——— Pronouns & basics ———
  { ar: "أنا", tr: "ana", en: "I", cat: "Basics", wik: "انا" },
  { ar: "إنت", tr: "inta / inti", en: "you (m/f)", cat: "Basics", wik: "انت" },
  { ar: "هو", tr: "huwwe", en: "he", cat: "Basics" },
  { ar: "هي", tr: "hiyye", en: "she", cat: "Basics" },
  { ar: "نحنا", tr: "niḥna", en: "we", cat: "Basics" },
  { ar: "إنتو", tr: "intu", en: "you (plural)", cat: "Basics", wik: "انتو" },
  { ar: "هنن", tr: "hinnen", en: "they (also هنّي / همه)", cat: "Basics" },
  { ar: "هاد", tr: "hād", en: "this (m)", cat: "Basics" },
  { ar: "هاي", tr: "hāy", en: "this (f)", cat: "Basics" },
  { ar: "هدول", tr: "hadōl", en: "these", cat: "Basics" },
  { ar: "هيك", tr: "hēk", en: "like this, so, this way", cat: "Basics" },
  { ar: "هون", tr: "hōn", en: "here", cat: "Basics" },
  { ar: "هونيك", tr: "honīk", en: "there, over there", cat: "Basics" },
  { ar: "في", tr: "fī", en: "there is, there are", cat: "Basics" },
  { ar: "ما في", tr: "mā fī", en: "there isn't, there aren't", cat: "Basics", wik: "ما في" },
  { ar: "مش", tr: "mish", en: "not (Syrian also: مو mū)", cat: "Basics" },

  // ——— Verbs & modals ———
  { ar: "بدي", tr: "biddi", en: "I want (biddak: you want)", cat: "Verbs", wik: "بد" },
  { ar: "فيي", tr: "fiyyi", en: "I can (fīk: you can)", cat: "Verbs", wik: "في" },
  { ar: "لازم", tr: "lāzim", en: "must, have to, should", cat: "Verbs" },
  { ar: "ممكن", tr: "mumkin", en: "possible; may I…?", cat: "Verbs" },
  { ar: "بقدر", tr: "biʾdir", en: "I can, I'm able to", cat: "Verbs", wik: "قدر" },
  { ar: "بحب", tr: "bḥibb", en: "I like, I love", cat: "Verbs", wik: "حب" },
  { ar: "بعرف", tr: "baʿrif", en: "I know", cat: "Verbs", wik: "عرف" },
  { ar: "بفهم", tr: "bifham", en: "I understand", cat: "Verbs", wik: "فهم" },
  { ar: "بحكي", tr: "baḥki", en: "I speak, I talk", cat: "Verbs", wik: "حكى" },
  { ar: "بروح", tr: "brūḥ", en: "I go", cat: "Verbs", wik: "راح" },
  { ar: "بجي", tr: "baji", en: "I come", cat: "Verbs", wik: "اجا" },
  { ar: "بشوف", tr: "bshūf", en: "I see", cat: "Verbs", wik: "شاف" },
  { ar: "بسمع", tr: "bismaʿ", en: "I hear, I listen", cat: "Verbs", wik: "سمع" },
  { ar: "باكل", tr: "bākul", en: "I eat", cat: "Verbs", wik: "اكل" },
  { ar: "بشرب", tr: "bishrab", en: "I drink", cat: "Verbs", wik: "شرب" },
  { ar: "بشتغل", tr: "bishtghil", en: "I work", cat: "Verbs", wik: "اشتغل" },
  { ar: "بسكن", tr: "buskun", en: "I live (reside)", cat: "Verbs", wik: "سكن" },
  { ar: "بدرس", tr: "budrus", en: "I study", cat: "Verbs", wik: "درس" },
  { ar: "بعمل", tr: "baʿmil", en: "I do, I make", cat: "Verbs", wik: "عمل" },
  { ar: "باخد", tr: "bākhud", en: "I take", cat: "Verbs", wik: "اخد" },
  { ar: "بعطي", tr: "baʿṭi", en: "I give", cat: "Verbs", wik: "عطى" },
  { ar: "عم", tr: "ʿam", en: "-ing (progressive: عم بحكي = I'm talking)", cat: "Verbs" },
  { ar: "رح", tr: "raḥ", en: "will (future: رح روح = I'll go)", cat: "Verbs" },
  { ar: "كان", tr: "kān", en: "he was; (it) was", cat: "Verbs" },
  { ar: "صار", tr: "ṣār", en: "became, happened, started", cat: "Verbs" },
  { ar: "راح", tr: "rāḥ", en: "he went", cat: "Verbs" },
  { ar: "إجا", tr: "ija", en: "he came", cat: "Verbs", wik: "اجا" },
  { ar: "قال", tr: "ʾāl", en: "he said", cat: "Verbs" },

  // ——— Everyday little words ———
  { ar: "هلق", tr: "hallaʾ", en: "now (also هلأ)", cat: "Everyday" },
  { ar: "لسا", tr: "lissa", en: "still; not yet", cat: "Everyday" },
  { ar: "شوي", tr: "shwayy", en: "a little, a bit", cat: "Everyday" },
  { ar: "كتير", tr: "ktīr", en: "a lot, very", cat: "Everyday" },
  { ar: "بس", tr: "bass", en: "but; only; enough!", cat: "Everyday" },
  { ar: "كمان", tr: "kamān", en: "also, too; more", cat: "Everyday" },
  { ar: "بكرا", tr: "bukra", en: "tomorrow", cat: "Everyday" },
  { ar: "مبارح", tr: "mbāriḥ", en: "yesterday", cat: "Everyday" },
  { ar: "اليوم", tr: "il-yōm", en: "today", cat: "Everyday" },
  { ar: "بعدين", tr: "baʿdēn", en: "later, afterwards; by the way", cat: "Everyday" },
  { ar: "قبل", tr: "ʾabl", en: "before", cat: "Everyday" },
  { ar: "بعد", tr: "baʿd", en: "after", cat: "Everyday" },
  { ar: "دايماً", tr: "dāyman", en: "always", cat: "Everyday", wik: "دايما" },
  { ar: "عنجد", tr: "ʿanjad", en: "really, seriously", cat: "Everyday" },
  { ar: "خلص", tr: "khalaṣ", en: "done!, that's it!, enough!", cat: "Everyday" },
  { ar: "طيب", tr: "ṭayyib", en: "OK, well…, alright", cat: "Everyday" },
  { ar: "ماشي", tr: "māshi", en: "OK, fine, deal", cat: "Everyday" },
  { ar: "يمكن", tr: "yimkin", en: "maybe, perhaps", cat: "Everyday" },
  { ar: "أكيد", tr: "akīd", en: "sure, definitely", cat: "Everyday", wik: "اكيد" },
  { ar: "سوا", tr: "sawa", en: "together", cat: "Everyday" },
  { ar: "لحالي", tr: "la-ḥāli", en: "by myself, alone", cat: "Everyday", wik: "لحال" },
  { ar: "مشان", tr: "mishān", en: "for, in order to, because of", cat: "Everyday" },
  { ar: "لأنه", tr: "laʾinno", en: "because", cat: "Everyday", wik: "لانه" },
  { ar: "يعني", tr: "yaʿni", en: "I mean…, that is, like, kind of", cat: "Everyday" },

  // ——— People ———
  { ar: "بابا", tr: "bāba", en: "dad", cat: "People" },
  { ar: "ماما", tr: "māma", en: "mom", cat: "People" },
  { ar: "أخ", tr: "akh", en: "brother", cat: "People", wik: "اخ" },
  { ar: "أخت", tr: "ukht", en: "sister", cat: "People", wik: "اخت" },
  { ar: "ابن", tr: "ibn", en: "son", cat: "People" },
  { ar: "بنت", tr: "bint", en: "girl; daughter", cat: "People" },
  { ar: "ولد", tr: "walad", en: "boy; child", cat: "People" },
  { ar: "زلمة", tr: "zalame", en: "man, guy", cat: "People" },
  { ar: "مرا", tr: "mara", en: "woman", cat: "People" },
  { ar: "صاحب", tr: "ṣāḥib", en: "friend (f: ṣāḥbe صاحبة)", cat: "People" },
  { ar: "جار", tr: "jār", en: "neighbor", cat: "People" },
  { ar: "عيلة", tr: "ʿēle", en: "family", cat: "People" },
  { ar: "جوز", tr: "jōz", en: "husband (wife: مرة marto = his wife)", cat: "People" },

  // ——— Food & drink ———
  { ar: "أكل", tr: "akl", en: "food", cat: "Food", wik: "اكل" },
  { ar: "مي", tr: "mayy", en: "water", cat: "Food" },
  { ar: "خبز", tr: "khubz", en: "bread", cat: "Food" },
  { ar: "قهوة", tr: "ʾahwe", en: "coffee", cat: "Food" },
  { ar: "شاي", tr: "shāy", en: "tea", cat: "Food" },
  { ar: "حليب", tr: "ḥalīb", en: "milk", cat: "Food" },
  { ar: "جبنة", tr: "jibne", en: "cheese", cat: "Food" },
  { ar: "زيتون", tr: "zētūn", en: "olives", cat: "Food" },
  { ar: "زيت", tr: "zēt", en: "oil (olive oil: زيت زيتون)", cat: "Food" },
  { ar: "سكر", tr: "sukkar", en: "sugar", cat: "Food" },
  { ar: "ملح", tr: "milḥ", en: "salt", cat: "Food" },
  { ar: "منقوشة", tr: "manʾūshe", en: "manousheh (zaatar flatbread)", cat: "Food" },

  // ——— Places & things ———
  { ar: "بيت", tr: "bēt", en: "house, home", cat: "Places" },
  { ar: "شغل", tr: "shughl", en: "work, job", cat: "Places" },
  { ar: "مدرسة", tr: "madrase", en: "school", cat: "Places" },
  { ar: "جامعة", tr: "jāmʿa", en: "university", cat: "Places" },
  { ar: "سيارة", tr: "sayyāra", en: "car", cat: "Places" },
  { ar: "شارع", tr: "shāriʿ", en: "street", cat: "Places" },
  { ar: "محل", tr: "maḥall", en: "shop, store", cat: "Places" },
  { ar: "سوق", tr: "sūʾ", en: "market", cat: "Places" },
  { ar: "مصاري", tr: "maṣāri", en: "money", cat: "Places" },
  { ar: "باص", tr: "bāṣ", en: "bus", cat: "Places" },
  { ar: "مطعم", tr: "maṭʿam", en: "restaurant", cat: "Places" },
  { ar: "تلفون", tr: "talifōn", en: "phone", cat: "Places" },

  // ——— Adjectives ———
  { ar: "كبير", tr: "kbīr", en: "big; old (person)", cat: "Adjectives" },
  { ar: "زغير", tr: "zghīr", en: "small; young", cat: "Adjectives" },
  { ar: "حلو", tr: "ḥilu", en: "nice, pretty; sweet", cat: "Adjectives" },
  { ar: "عاطل", tr: "ʿāṭil", en: "bad, no good", cat: "Adjectives" },
  { ar: "جديد", tr: "jdīd", en: "new", cat: "Adjectives" },
  { ar: "قديم", tr: "ʾadīm", en: "old (things)", cat: "Adjectives" },
  { ar: "حامي", tr: "ḥāmi", en: "hot", cat: "Adjectives" },
  { ar: "بارد", tr: "bārid", en: "cold", cat: "Adjectives" },
  { ar: "تعبان", tr: "taʿbān", en: "tired", cat: "Adjectives" },
  { ar: "جوعان", tr: "jūʿān", en: "hungry", cat: "Adjectives" },
  { ar: "عطشان", tr: "ʿaṭshān", en: "thirsty", cat: "Adjectives" },
  { ar: "مبسوط", tr: "mabsūṭ", en: "happy, pleased", cat: "Adjectives" },
  { ar: "زعلان", tr: "zaʿlān", en: "sad, upset", cat: "Adjectives" },
  { ar: "مشغول", tr: "mashghūl", en: "busy", cat: "Adjectives" },
  { ar: "رخيص", tr: "rkhīṣ", en: "cheap", cat: "Adjectives" },
  { ar: "غالي", tr: "ghāli", en: "expensive; dear", cat: "Adjectives" },
  { ar: "قريب", tr: "ʾarīb", en: "near, close", cat: "Adjectives" },
  { ar: "بعيد", tr: "bʿīd", en: "far", cat: "Adjectives" },
  { ar: "سهل", tr: "sahl", en: "easy", cat: "Adjectives" },
  { ar: "صعب", tr: "ṣaʿb", en: "difficult, hard", cat: "Adjectives" },

  // ——— Time ———
  { ar: "يوم", tr: "yōm", en: "day", cat: "Time" },
  { ar: "أسبوع", tr: "usbūʿ", en: "week", cat: "Time", wik: "اسبوع" },
  { ar: "شهر", tr: "shahr", en: "month", cat: "Time" },
  { ar: "سنة", tr: "sine", en: "year", cat: "Time" },
  { ar: "ساعة", tr: "sāʿa", en: "hour; watch, clock", cat: "Time" },
  { ar: "دقيقة", tr: "daʾīʾa", en: "minute", cat: "Time" },
  { ar: "الصبح", tr: "iṣ-ṣubḥ", en: "(in) the morning", cat: "Time", wik: "صبح" },
  { ar: "المسا", tr: "il-masa", en: "(in) the evening", cat: "Time", wik: "مسا" },
  { ar: "ليل", tr: "lēl", en: "night", cat: "Time" },
  { ar: "وقت", tr: "waʾt", en: "time", cat: "Time" },

  // ——— Numbers ———
  { ar: "واحد", tr: "wāḥad", en: "one", cat: "Numbers" },
  { ar: "تنين", tr: "tnēn", en: "two", cat: "Numbers" },
  { ar: "تلاتة", tr: "tlāte", en: "three", cat: "Numbers" },
  { ar: "أربعة", tr: "arbʿa", en: "four", cat: "Numbers", wik: "اربعة" },
  { ar: "خمسة", tr: "khamse", en: "five", cat: "Numbers" },
  { ar: "ستة", tr: "sitte", en: "six", cat: "Numbers" },
  { ar: "سبعة", tr: "sabʿa", en: "seven", cat: "Numbers" },
  { ar: "تمانة", tr: "tamāne", en: "eight", cat: "Numbers" },
  { ar: "تسعة", tr: "tisʿa", en: "nine", cat: "Numbers" },
  { ar: "عشرة", tr: "ʿashara", en: "ten", cat: "Numbers" },
].map((w, i) => ({ id: i, ...w }));

const TEXTS = [
  {
    id: "intro",
    title: "Meeting someone",
    titleAr: "التعارف",
    level: "A1",
    lines: [
      { sp: "سامر", ar: "مرحبا!", en: "Hi!" },
      { sp: "ليلى", ar: "أهلين! كيفك؟", en: "Hi! How are you?" },
      { sp: "سامر", ar: "منيح الحمد لله، وإنتِ كيفك؟", en: "Fine, thank God — and you, how are you?" },
      { sp: "ليلى", ar: "تمام. شو اسمك؟", en: "Great. What's your name?" },
      { sp: "سامر", ar: "اسمي سامر. وإنتِ؟", en: "My name is Samer. And you?" },
      { sp: "ليلى", ar: "أنا ليلى. من وين إنت؟", en: "I'm Layla. Where are you from?" },
      { sp: "سامر", ar: "أنا من عمان. وإنتِ من وين؟", en: "I'm from Amman. And where are you from?" },
      { sp: "ليلى", ar: "أنا من بيروت، بس ساكنة هون من سنتين.", en: "I'm from Beirut, but I've been living here for two years." },
      { sp: "سامر", ar: "حلو كتير! تشرفنا.", en: "Very nice! Pleased to meet you." },
      { sp: "ليلى", ar: "تشرفنا فيك.", en: "Pleased to meet you too." },
    ],
  },
  {
    id: "cafe",
    title: "At the café",
    titleAr: "بالقهوة",
    level: "A1",
    lines: [
      { sp: "الغرسون", ar: "أهلا وسهلا! شو بتحبوا تشربوا؟", en: "Welcome! What would you like to drink?" },
      { sp: "رنا", ar: "بدي قهوة لو سمحت.", en: "I'd like a coffee, please." },
      { sp: "الغرسون", ar: "سادة ولا مع سكر؟", en: "Black, or with sugar?" },
      { sp: "رنا", ar: "مظبوطة، لو سمحت.", en: "Medium-sweet, please." },
      { sp: "فادي", ar: "وأنا بدي شاي مع نعنع.", en: "And I'd like tea with mint." },
      { sp: "الغرسون", ar: "ماشي. في شي تاني؟", en: "Sure. Anything else?" },
      { sp: "فادي", ar: "قديش صحن الحمص؟", en: "How much is the plate of hummus?" },
      { sp: "الغرسون", ar: "بدينارين.", en: "Two dinars." },
      { sp: "فادي", ar: "طيب، جيبلنا صحن حمص كمان.", en: "OK, bring us a plate of hummus too." },
      { sp: "الغرسون", ar: "تكرم، دقيقة وبكون عندكم.", en: "Of course — one minute and I'll be right with you." },
    ],
  },
  {
    id: "market",
    title: "At the market",
    titleAr: "بالسوق",
    level: "A2",
    lines: [
      { sp: "الزبونة", ar: "مرحبا، قديش كيلو البندورة؟", en: "Hi, how much is a kilo of tomatoes?" },
      { sp: "البياع", ar: "أهلين، الكيلو بدينار.", en: "Hello — one dinar a kilo." },
      { sp: "الزبونة", ar: "غالي شوي! عندك أرخص؟", en: "A bit expensive! Do you have anything cheaper?" },
      { sp: "البياع", ar: "هاي بندورة بلدية يا ستي، أحلى شي بالسوق.", en: "These are local tomatoes, ma'am — the best in the market." },
      { sp: "الزبونة", ar: "طيب عطيني كيلوين، وكيلو خيار كمان.", en: "Fine, give me two kilos, and a kilo of cucumbers too." },
      { sp: "البياع", ar: "تكرمي. بدك شي تاني؟", en: "Of course. Do you want anything else?" },
      { sp: "الزبونة", ar: "لا خلص، هيك منيح. قديش صار المجموع؟", en: "No, that's it, this is fine. What does the total come to?" },
      { sp: "البياع", ar: "تلاتة ونص.", en: "Three and a half." },
      { sp: "الزبونة", ar: "تفضل. يعطيك العافية.", en: "Here you go. Thank you (may God give you strength)." },
      { sp: "البياع", ar: "الله يعافيكي.", en: "And you (the reply)." },
    ],
  },
  {
    id: "myday",
    title: "My day",
    titleAr: "يومي",
    level: "A2",
    lines: [
      { ar: "كل يوم بصحى الساعة سبعة الصبح.", en: "Every day I wake up at seven in the morning." },
      { ar: "بشرب قهوتي وباكل شي خفيف.", en: "I drink my coffee and eat something light." },
      { ar: "بعدين بروح عالشغل بالباص.", en: "Then I go to work by bus." },
      { ar: "الطريق بياخد شي نص ساعة.", en: "The trip takes about half an hour." },
      { ar: "بشتغل من الساعة تمانة لأربعة.", en: "I work from eight o'clock to four." },
      { ar: "بعد الشغل، أحياناً بلتقي مع صحابي.", en: "After work, sometimes I meet up with my friends." },
      { ar: "منقعد بمقهى ومنحكي عن كل شي.", en: "We sit in a café and talk about everything." },
      { ar: "بالليل برجع عالبيت تعبان بس مبسوط.", en: "At night I come back home tired but happy." },
    ],
  },
  {
    id: "phone",
    title: "On the phone",
    titleAr: "عالتلفون",
    level: "A2",
    lines: [
      { sp: "ريم", ar: "ألو؟ مرحبا نور!", en: "Hello? Hi Nour!" },
      { sp: "نور", ar: "أهلين ريم! كيفك؟ شو أخبارك؟", en: "Hey Reem! How are you? What's new?" },
      { sp: "ريم", ar: "تمام. شو رأيك نطلع بكرا؟", en: "Fine. What do you think about going out tomorrow?" },
      { sp: "نور", ar: "فكرة حلوة! وين بدك تروحي؟", en: "Nice idea! Where do you want to go?" },
      { sp: "ريم", ar: "في مطعم جديد جنب البحر، بقولوا أكله كتير طيب.", en: "There's a new restaurant by the sea — they say its food is really good." },
      { sp: "نور", ar: "ماشي، بس بكرا عندي شغل للساعة خمسة.", en: "OK, but tomorrow I have work until five o'clock." },
      { sp: "ريم", ar: "ولا يهمك، منروح الساعة سبعة.", en: "No worries, we'll go at seven." },
      { sp: "نور", ar: "عنجد ممتاز. بتحبي إجي آخدك بالسيارة؟", en: "Really great. Would you like me to come pick you up by car?" },
      { sp: "ريم", ar: "أكيد، بستناكي قدام البيت.", en: "Sure, I'll wait for you in front of the house." },
      { sp: "نور", ar: "اتفقنا! منشوفك بكرا.", en: "Deal! See you tomorrow." },
    ],
  },
  {
    id: "trip",
    title: "A trip to the mountains",
    titleAr: "مشوار عالجبل",
    level: "B1",
    lines: [
      { ar: "الجمعة الماضية، أنا وعيلتي طلعنا مشوار عالجبل.", en: "Last Friday, my family and I went on a trip to the mountains." },
      { ar: "صحينا بكير، حضّرنا الأكل، وركبنا بالسيارة.", en: "We woke up early, prepared the food, and got in the car." },
      { ar: "الطريق كان حلو كتير، والطقس ولا أحلى.", en: "The road was really beautiful, and the weather couldn't have been better." },
      { ar: "لما وصلنا، قعدنا تحت شجرة كبيرة وشربنا شاي.", en: "When we arrived, we sat under a big tree and drank tea." },
      { ar: "الولاد لعبوا وركضوا، ونحنا حكينا وضحكنا.", en: "The kids played and ran around, and we talked and laughed." },
      { ar: "عالضهر أكلنا مناقيش وسلطة وفواكه.", en: "At noon we ate manakish, salad, and fruit." },
      { ar: "قبل ما نرجع، أخدنا صور كتير للغروب.", en: "Before heading back, we took lots of photos of the sunset." },
      { ar: "رجعنا عالبيت بالليل تعبانين، بس كان يوم ما بينتسى.", en: "We got back home at night exhausted, but it was an unforgettable day." },
    ],
  },
];
