// Levantine Arabic (شامي) learning data.
// Transliteration: ḥ ṭ ṣ ḍ ʿ ʾ, long vowels ā ē ī ō ū.
// `wik` overrides the Wiktionary page title when it differs from `ar`.

// Fold the spelling variants that stop a word matching itself — the same rules
// tools/build_audio.py applies when it names a clip, so a word here and its
// recording in audio/manifest.json always meet.
function normAr(s) {
  return s.normalize("NFC")
    .replace(/[\u064B-\u0652\u0670\u0640]/g, "")
    .replace(/[\u0623\u0625\u0622\u0671]/g, "\u0627")
    .replace(/\u0649/g, "\u064A").replace(/\u0624/g, "\u0648").replace(/\u0626/g, "\u064A")
    .replace(/[\u061F!\u060C.,?]/g, "")
    .replace(/\s+/g, " ").trim();
}

// Lessons drawn from the Lingua Libre corpus: every word here has a recording
// by a native South Levantine speaker. Built by tools/build_audio.py — the
// Arabic must match audio/manifest.json exactly, so regenerate rather than
// hand-editing when the selection changes.
const LESSONS = [
  {
    id: "people",
    title: "People & politeness",
    words: [
    { ar: "اجنبي", tr: "ajnabi", en: "foreign; a foreigner" },
    { ar: "احنا", tr: "iḥna", en: "we" },
    { ar: "آسف", tr: "āsif", en: "sorry (m)" },
    { ar: "اسم", tr: "ism", en: "name" },
    { ar: "اشخاص", tr: "ashkhāṣ", en: "people, persons" },
    { ar: "اصحاب", tr: "aṣḥāb", en: "friends; owners" },
    { ar: "اصدقاء", tr: "aṣdiqāʾ", en: "friends" },
    { ar: "انا", tr: "ana", en: "I" },
    { ar: "انتا", tr: "inta", en: "you (m)" },
    { ar: "انتو", tr: "into", en: "you (pl)" },
    { ar: "انتي", tr: "inti", en: "you (f)" },
    { ar: "اهل", tr: "ahl", en: "family, parents; folks" },
    { ar: "بدون", tr: "bidūn", en: "without" },
    { ar: "برضه", tr: "barḍo", en: "also, too; anyway" },
    { ar: "بِسّ", tr: "bass", en: "but; only; enough" },
    { ar: "بعض", tr: "baʿḍ", en: "some; each other" },
    { ar: "بعيد", tr: "baʿīd", en: "far" },
    { ar: "بلا", tr: "bala", en: "without; forget it" },
    { ar: "بلاش", tr: "balāsh", en: "don't; for free; never mind" },
    { ar: "بما انّه", tr: "bimā innu", en: "since, given that" },
    { ar: "بنات", tr: "banāt", en: "girls" },
    { ar: "بنت", tr: "bint", en: "girl; daughter" },
    { ar: "بني ادم", tr: "bani ādam", en: "human being, person" },
    { ar: "بين", tr: "bēn", en: "between" },
    { ar: "بينما", tr: "baynamā", en: "while, whereas" },
    { ar: "تحت", tr: "taḥt", en: "under, below" },
    { ar: "تمام", tr: "tamām", en: "fine, perfect, OK" },
    { ar: "حبيب", tr: "ḥabīb", en: "dear, beloved" },
    { ar: "حتّى", tr: "ḥatta", en: "until; even" },
    { ar: "حلو", tr: "ḥilu", en: "nice, pretty, sweet" },
    { ar: "حياة", tr: "ḥayāh", en: "life" },
    { ar: "دغري", tr: "dughri", en: "straight ahead; straightforward" },
    { ar: "زلمة", tr: "zalame", en: "man, guy" },
    { ar: "شاطر", tr: "shāṭir", en: "clever, good at something" },
    { ar: "شبّ", tr: "shabb", en: "young man" },
    { ar: "شباب", tr: "shabāb", en: "young people, guys" },
    { ar: "شخص", tr: "shakhṣ", en: "person" },
    { ar: "شكرًا", tr: "shukran", en: "thank you" },
    { ar: "شمال", tr: "shmāl", en: "left; north" },
    { ar: "صاحب", tr: "ṣāḥib", en: "friend; owner" },
    { ar: "صبية", tr: "ṣabiyye", en: "young woman" },
    { ar: "صديق", tr: "ṣadīq", en: "friend" },
    { ar: "طالما", tr: "ṭālama", en: "as long as" },
    { ar: "طيّب", tr: "ṭayyib", en: "good, kind; OK then" },
    { ar: "عادي", tr: "ʿādi", en: "normal; no big deal" },
    { ar: "عُرس", tr: "ʿurs", en: "wedding" },
    { ar: "عَروس", tr: "ʿarūs", en: "bride" },
    { ar: "عَريس", tr: "ʿarīs", en: "groom" },
    { ar: "عزيز", tr: "ʿazīz", en: "dear, precious" },
    { ar: "عشان", tr: "ʿashān", en: "because; in order to" },
    { ar: "عفوًا", tr: "ʿafwan", en: "you're welcome; excuse me" },
    { ar: "علاقة", tr: "ʿalāqa", en: "relationship" },
    { ar: "عمر", tr: "ʿumr", en: "age; lifetime" },
    { ar: "عيلة", tr: "ʿēle", en: "family" },
    { ar: "غريب", tr: "gharīb", en: "strange; a stranger" },
    { ar: "غير", tr: "ghēr", en: "other than; different" },
    { ar: "فوق", tr: "fōʾ", en: "above, up" },
    { ar: "في", tr: "fī", en: "in; there is" },
    { ar: "فيه", tr: "fīh", en: "there is; in it" },
    { ar: "قدّام", tr: "ʾuddām", en: "in front of" },
    { ar: "قريب", tr: "ʾarīb", en: "near; soon; a relative" },
    { ar: "كمان", tr: "kamān", en: "also, too; again" },
    { ar: "كويّس", tr: "kwayyis", en: "good, nice" },
    { ar: "لحدّ", tr: "la-ḥadd", en: "until, up to" },
    { ar: "لطيف", tr: "laṭīf", en: "kind, pleasant" },
    { ar: "للأسف", tr: "lil-ʾasaf", en: "unfortunately" },
    { ar: "لو سمحت", tr: "law samaḥt", en: "please; excuse me" },
    { ar: "ما دام", tr: "mā dām", en: "as long as" },
    { ar: "متأسّف", tr: "mitʾassif", en: "sorry (m)" },
    { ar: "مرّة", tr: "marra", en: "a time, once" },
    { ar: "مع", tr: "maʿ", en: "with" },
    { ar: "معليش", tr: "maʿlēsh", en: "never mind, it's OK" },
    { ar: "منشان", tr: "minshān", en: "for; in order to" },
    { ar: "منيح", tr: "mnīḥ", en: "good, fine, well" },
    { ar: "همه", tr: "humme", en: "they" },
    { ar: "هناك", tr: "hunāk", en: "there" },
    { ar: "هو", tr: "huwwe", en: "he" },
    { ar: "هون", tr: "hōn", en: "here" },
    { ar: "هوية", tr: "hawiyye", en: "identity; ID card" },
    { ar: "هي", tr: "hiyye", en: "she" },
    { ar: "ورا", tr: "wara", en: "behind" },
    { ar: "ولاد", tr: "wlād", en: "children, boys" },
    { ar: "ولد", tr: "walad", en: "boy, child" },
    { ar: "يمين", tr: "yamīn", en: "right (direction)" },
    ],
  },
  {
    id: "food",
    title: "Food & drink",
    words: [
    { ar: "اكل", tr: "akl", en: "food; eating" },
    { ar: "باتنجان", tr: "bātinjān", en: "aubergine, eggplant" },
    { ar: "برقوق", tr: "barʾūʾ", en: "plums" },
    { ar: "بصل", tr: "baṣal", en: "onions" },
    { ar: "بطّيخ", tr: "baṭṭīkh", en: "watermelon" },
    { ar: "بندورة", tr: "banadōra", en: "tomatoes" },
    { ar: "بهار", tr: "bhār", en: "spice, seasoning" },
    { ar: "تفّاح", tr: "tuffāḥ", en: "apples" },
    { ar: "تمر", tr: "tamr", en: "dates" },
    { ar: "جبنة", tr: "jibne", en: "cheese" },
    { ar: "جزر", tr: "jazar", en: "carrots" },
    { ar: "حليب", tr: "ḥalīb", en: "milk" },
    { ar: "خُبز", tr: "khubz", en: "bread" },
    { ar: "خسّ", tr: "khass", en: "lettuce" },
    { ar: "خضار", tr: "khuḍār", en: "vegetables" },
    { ar: "خوخ", tr: "khōkh", en: "peaches" },
    { ar: "خيار", tr: "khiyār", en: "cucumbers" },
    { ar: "زبدة", tr: "zibde", en: "butter" },
    { ar: "زنجبيل", tr: "zanjabīl", en: "ginger" },
    { ar: "زيت", tr: "zēt", en: "oil" },
    { ar: "زيتون", tr: "zaytūn", en: "olives" },
    { ar: "سكّينة", tr: "sikkīne", en: "knife" },
    { ar: "شاي", tr: "shāy", en: "tea" },
    { ar: "شوربة", tr: "shōrba", en: "soup" },
    { ar: "شوكة", tr: "shōke", en: "fork" },
    { ar: "صحن", tr: "ṣaḥn", en: "plate" },
    { ar: "طعم", tr: "ṭaʿm", en: "taste, flavour" },
    { ar: "عسل", tr: "ʿasal", en: "honey" },
    { ar: "عشا", tr: "ʿasha", en: "dinner" },
    { ar: "عصير", tr: "ʿaṣīr", en: "juice" },
    { ar: "عنب", tr: "ʿinab", en: "grapes" },
    { ar: "غدا", tr: "ghada", en: "lunch" },
    { ar: "فاسد", tr: "fāsid", en: "spoiled, off" },
    { ar: "فاصوليا", tr: "fāṣūlya", en: "beans" },
    { ar: "فطور", tr: "fṭūr", en: "breakfast" },
    { ar: "فلفل", tr: "filfil", en: "pepper" },
    { ar: "فنجان", tr: "finjān", en: "small coffee cup" },
    { ar: "فواكه", tr: "fawākih", en: "fruit" },
    { ar: "قشطة", tr: "ʾishṭa", en: "cream" },
    { ar: "قنّينة", tr: "ʾannīne", en: "bottle" },
    { ar: "قهوة", tr: "ʾahwe", en: "coffee" },
    { ar: "كاسة", tr: "kāse", en: "glass, cup" },
    { ar: "كبّاية", tr: "kubbāye", en: "drinking glass" },
    { ar: "ليمون", tr: "laymūn", en: "lemon; citrus" },
    { ar: "مرميّة", tr: "maryamiyye", en: "sage (herbal tea)" },
    { ar: "مشروب", tr: "mashrūb", en: "a drink" },
    { ar: "مشمش", tr: "mishmish", en: "apricots" },
    { ar: "مَطبَخ", tr: "maṭbakh", en: "kitchen" },
    { ar: "مطعم", tr: "maṭʿam", en: "restaurant" },
    { ar: "معلقة", tr: "malʿaʾa", en: "spoon" },
    { ar: "مقهى", tr: "maʾha", en: "café" },
    { ar: "ملفوف", tr: "malfūf", en: "cabbage" },
    { ar: "مي", tr: "mayy", en: "water" },
    { ar: "نبيد", tr: "nbīd", en: "wine" },
    { ar: "نعنع", tr: "naʿnaʿ", en: "mint" },
    ],
  },
  {
    id: "time",
    title: "Time",
    words: [
    { ar: "ابَدًا", tr: "abadan", en: "never; not at all" },
    { ar: "آخِر", tr: "ākhir", en: "last, final; the end of" },
    { ar: "اخيرًا", tr: "akhīran", en: "finally, at last" },
    { ar: "اُسبوع", tr: "usbūʿ", en: "week" },
    { ar: "الليلة", tr: "il-lēle", en: "tonight" },
    { ar: "اليوم", tr: "il-yōm", en: "today" },
    { ar: "بدري", tr: "badri", en: "early" },
    { ar: "بَعد", tr: "baʿd", en: "after; still, yet" },
    { ar: "بعدين", tr: "baʿdēn", en: "later, afterwards" },
    { ar: "بُكرا", tr: "bukra", en: "tomorrow" },
    { ar: "بَكّير", tr: "bakkīr", en: "early" },
    { ar: "تلاتة", tr: "talāte", en: "three" },
    { ar: "تنتين", tr: "tintēn", en: "two (f)" },
    { ar: "ثانية", tr: "thānye", en: "a second" },
    { ar: "حاليًا", tr: "ḥāliyyan", en: "currently, at present" },
    { ar: "دايمًا", tr: "dāyman", en: "always" },
    { ar: "دَقيقة", tr: "daʾīʾa", en: "a minute" },
    { ar: "زَمان", tr: "zamān", en: "long ago; time" },
    { ar: "ساعة", tr: "sāʿa", en: "hour; watch, clock" },
    { ar: "سَنة", tr: "sane", en: "year" },
    { ar: "شَهر", tr: "shahr", en: "month" },
    { ar: "صَباحيّة", tr: "ṣabāḥiyye", en: "the morning" },
    { ar: "صُبُح", tr: "ṣubuḥ", en: "morning" },
    { ar: "فَترة", tr: "fatra", en: "a period, a while" },
    { ar: "قَبل", tr: "ʾabl", en: "before" },
    { ar: "لَحظة", tr: "laḥẓa", en: "a moment" },
    { ar: "لِسّا", tr: "lissa", en: "still; not yet" },
    { ar: "ليل", tr: "lēl", en: "night-time" },
    { ar: "ليلة", tr: "lēle", en: "a night" },
    { ar: "ماضي", tr: "māḍi", en: "past" },
    { ar: "مبارِح", tr: "mbāriḥ", en: "yesterday" },
    { ar: "متأخِّر", tr: "mitʾakhkhir", en: "late" },
    { ar: "مُدّة", tr: "mudde", en: "a period, duration" },
    { ar: "مَسا", tr: "masa", en: "evening" },
    { ar: "مستقبل", tr: "mustaʾbal", en: "future" },
    { ar: "نادِرًا", tr: "nādiran", en: "rarely" },
    { ar: "نهار", tr: "nhār", en: "daytime" },
    { ar: "وَقت", tr: "waʾt", en: "time" },
    { ar: "يوم", tr: "yōm", en: "day" },
    ],
  },
];


const VOCAB = (() => {
  const base = [
  // ——— Greetings & politeness ———
  { ar: "مرحبا", tr: "marḥaba", en: "hi, hello", cat: "Greetings" },
  { ar: "أهلين", tr: "ahlēn", en: "hi! (warm reply to marḥaba)", cat: "Greetings", wik: "اهلين" },
  { ar: "منيح", tr: "mnīḥ", en: "good, fine, well (f: mnīḥa)", cat: "Greetings" },
  { ar: "تمام", tr: "tamām", en: "fine, perfect, OK", cat: "Greetings" },
  { ar: "الحمد لله", tr: "il-ḥamdilla", en: "thank God; (I'm) fine", cat: "Greetings", wik: "الحمد لله" },
  { ar: "شكراً", tr: "shukran", en: "thank you", cat: "Greetings", wik: "شكرا" },
  { ar: "لو سمحت", tr: "law samaḥt", en: "please; excuse me", cat: "Greetings", wik: "لو سمحت" },
  { ar: "مع السلامة", tr: "maʿ is-salāme", en: "goodbye", cat: "Greetings", wik: "مع السلامة" },
  { ar: "يلا", tr: "yaḷḷa", en: "come on!, let's go!", cat: "Greetings" },
  { ar: "معليش", tr: "maʿlēsh", en: "never mind, it's OK, sorry", cat: "Greetings" },
  { ar: "مبروك", tr: "mabrūk", en: "congratulations!", cat: "Greetings" },
  { ar: "أهلا وسهلا", tr: "ahla w sahla", en: "welcome!", cat: "Greetings", wik: "اهلا وسهلا" },

  // ——— Question words ———
  { ar: "شو", tr: "shū", en: "what?", cat: "Questions" },
  { ar: "ليش", tr: "lēsh", en: "why?", cat: "Questions" },
  { ar: "وين", tr: "wēn", en: "where?", cat: "Questions" },
  { ar: "كيف", tr: "kīf", en: "how?", cat: "Questions" },
  { ar: "مين", tr: "mīn", en: "who?", cat: "Questions" },
  { ar: "قديش", tr: "addēsh", en: "how much?, how many?", cat: "Questions" },
  { ar: "أي", tr: "ayya", en: "which?", cat: "Questions", wik: "اي" },

  // ——— Pronouns & basics ———
  { ar: "أنا", tr: "ana", en: "I", cat: "Basics", wik: "انا" },
  { ar: "هو", tr: "huwwe", en: "he", cat: "Basics" },
  { ar: "هي", tr: "hiyye", en: "she", cat: "Basics" },
  { ar: "إنتو", tr: "intu", en: "you (plural)", cat: "Basics", wik: "انتو" },
  { ar: "هدول", tr: "hadōl", en: "these", cat: "Basics" },
  { ar: "هيك", tr: "hēk", en: "like this, so, this way", cat: "Basics" },
  { ar: "هون", tr: "hōn", en: "here", cat: "Basics" },
  { ar: "في", tr: "fī", en: "there is, there are", cat: "Basics" },
  { ar: "مش", tr: "mish", en: "not (Syrian also: مو mū)", cat: "Basics" },

  // ——— Verbs & modals ———
  { ar: "بدي", tr: "biddi", en: "I want (biddak: you want)", cat: "Verbs", wik: "بد" },
  { ar: "لازم", tr: "lāzim", en: "must, have to, should", cat: "Verbs" },
  { ar: "ممكن", tr: "mumkin", en: "possible; may I…?", cat: "Verbs" },
  { ar: "بشتغل", tr: "bishtghil", en: "I work", cat: "Verbs", wik: "اشتغل" },
  { ar: "عم", tr: "ʿam", en: "-ing (progressive: عم بحكي = I'm talking)", cat: "Verbs" },
  { ar: "رح", tr: "raḥ", en: "will (future: رح روح = I'll go)", cat: "Verbs" },

  // ——— Everyday little words ———
  { ar: "لسا", tr: "lissa", en: "still; not yet", cat: "Everyday" },
  { ar: "شوي", tr: "shwayy", en: "a little, a bit", cat: "Everyday" },
  { ar: "كتير", tr: "ktīr", en: "a lot, very", cat: "Everyday" },
  { ar: "بس", tr: "bass", en: "but; only; enough!", cat: "Everyday" },
  { ar: "كمان", tr: "kamān", en: "also, too; more", cat: "Everyday" },
  { ar: "بكرا", tr: "bukra", en: "tomorrow", cat: "Everyday" },
  { ar: "مبارح", tr: "mbāriḥ", en: "yesterday", cat: "Everyday" },
  { ar: "اليوم", tr: "il-yōm", en: "today", cat: "Everyday" },
  { ar: "بعدين", tr: "baʿdēn", en: "later, afterwards; by the way", cat: "Everyday" },
  { ar: "قبل", tr: "ʾabl", en: "before", cat: "Everyday" },
  { ar: "بعد", tr: "baʿd", en: "after", cat: "Everyday" },
  { ar: "دايماً", tr: "dāyman", en: "always", cat: "Everyday", wik: "دايما" },
  { ar: "طيب", tr: "ṭayyib", en: "OK, well…, alright", cat: "Everyday" },
  { ar: "يمكن", tr: "yimkin", en: "maybe, perhaps", cat: "Everyday" },
  { ar: "سوا", tr: "sawa", en: "together", cat: "Everyday" },
  { ar: "يعني", tr: "yaʿni", en: "I mean…, that is, like, kind of", cat: "Everyday" },

  // ——— People ———
  { ar: "بابا", tr: "bāba", en: "dad", cat: "People" },
  { ar: "ماما", tr: "māma", en: "mom", cat: "People" },
  { ar: "بنت", tr: "bint", en: "girl; daughter", cat: "People" },
  { ar: "ولد", tr: "walad", en: "boy; child", cat: "People" },
  { ar: "زلمة", tr: "zalame", en: "man, guy", cat: "People" },
  { ar: "صاحب", tr: "ṣāḥib", en: "friend (f: ṣāḥbe صاحبة)", cat: "People" },
  { ar: "جار", tr: "jār", en: "neighbor", cat: "People" },
  { ar: "عيلة", tr: "ʿēle", en: "family", cat: "People" },

  // ——— Food & drink ———
  { ar: "أكل", tr: "akl", en: "food", cat: "Food", wik: "اكل" },
  { ar: "مي", tr: "mayy", en: "water", cat: "Food" },
  { ar: "خبز", tr: "khubz", en: "bread", cat: "Food" },
  { ar: "قهوة", tr: "ʾahwe", en: "coffee", cat: "Food" },
  { ar: "شاي", tr: "shāy", en: "tea", cat: "Food" },
  { ar: "حليب", tr: "ḥalīb", en: "milk", cat: "Food" },
  { ar: "جبنة", tr: "jibne", en: "cheese", cat: "Food" },
  { ar: "زيتون", tr: "zētūn", en: "olives", cat: "Food" },
  { ar: "زيت", tr: "zēt", en: "oil (olive oil: زيت زيتون)", cat: "Food" },

  // ——— Places & things ———
  { ar: "بيت", tr: "bēt", en: "house, home", cat: "Places" },
  { ar: "شغل", tr: "shughl", en: "work, job", cat: "Places" },
  { ar: "مدرسة", tr: "madrase", en: "school", cat: "Places" },
  { ar: "جامعة", tr: "jāmʿa", en: "university", cat: "Places" },
  { ar: "سيارة", tr: "sayyāra", en: "car", cat: "Places" },
  { ar: "شارع", tr: "shāriʿ", en: "street", cat: "Places" },
  { ar: "محل", tr: "maḥall", en: "shop, store", cat: "Places" },
  { ar: "سوق", tr: "sūʾ", en: "market", cat: "Places" },
  { ar: "مصاري", tr: "maṣāri", en: "money", cat: "Places" },
  { ar: "باص", tr: "bāṣ", en: "bus", cat: "Places" },
  { ar: "مطعم", tr: "maṭʿam", en: "restaurant", cat: "Places" },
  { ar: "تلفون", tr: "talifōn", en: "phone", cat: "Places" },

  // ——— Adjectives ———
  { ar: "كبير", tr: "kbīr", en: "big; old (person)", cat: "Adjectives" },
  { ar: "زغير", tr: "zghīr", en: "small; young", cat: "Adjectives" },
  { ar: "حلو", tr: "ḥilu", en: "nice, pretty; sweet", cat: "Adjectives" },
  { ar: "جديد", tr: "jdīd", en: "new", cat: "Adjectives" },
  { ar: "قديم", tr: "ʾadīm", en: "old (things)", cat: "Adjectives" },
  { ar: "حامي", tr: "ḥāmi", en: "hot", cat: "Adjectives" },
  { ar: "بارد", tr: "bārid", en: "cold", cat: "Adjectives" },
  { ar: "مبسوط", tr: "mabsūṭ", en: "happy, pleased", cat: "Adjectives" },
  { ar: "مشغول", tr: "mashghūl", en: "busy", cat: "Adjectives" },
  { ar: "رخيص", tr: "rkhīṣ", en: "cheap", cat: "Adjectives" },
  { ar: "غالي", tr: "ghāli", en: "expensive; dear", cat: "Adjectives" },
  { ar: "قريب", tr: "ʾarīb", en: "near, close", cat: "Adjectives" },
  { ar: "بعيد", tr: "bʿīd", en: "far", cat: "Adjectives" },
  { ar: "سهل", tr: "sahl", en: "easy", cat: "Adjectives" },
  { ar: "صعب", tr: "ṣaʿb", en: "difficult, hard", cat: "Adjectives" },

  // ——— Time ———
  { ar: "يوم", tr: "yōm", en: "day", cat: "Time" },
  { ar: "أسبوع", tr: "usbūʿ", en: "week", cat: "Time", wik: "اسبوع" },
  { ar: "شهر", tr: "shahr", en: "month", cat: "Time" },
  { ar: "سنة", tr: "sine", en: "year", cat: "Time" },
  { ar: "ساعة", tr: "sāʿa", en: "hour; watch, clock", cat: "Time" },
  { ar: "دقيقة", tr: "daʾīʾa", en: "minute", cat: "Time" },
  { ar: "ليل", tr: "lēl", en: "night", cat: "Time" },
  { ar: "وقت", tr: "waʾt", en: "time", cat: "Time" },

  // ——— Numbers ———
  { ar: "تلاتة", tr: "tlāte", en: "three", cat: "Numbers" },
  ];
  // Lesson words the older list already covers keep their original entry — it
  // carries a Wiktionary override and the learner's progress, and it picks up
  // the native recording anyway through the same clip index.
  const seen = new Set(base.map(w => normAr(w.ar)));
  for (const lesson of LESSONS) {
    for (const w of lesson.words) {
      const key = normAr(w.ar);
      if (seen.has(key)) continue;
      seen.add(key);
      base.push({ ...w, cat: lesson.title, lesson: lesson.id });
    }
  }
  return base.map((w, i) => ({ id: i, ...w }));
})();

const TEXTS = [
  {
    id: "intro",
    title: "Meeting someone",
    titleAr: "التعارف",
    level: "A1",
    lines: [
      { sp: "سامر", ar: "مرحبا!", en: "Hi!" },
      { sp: "ليلى", ar: "أهلين! كيفك؟", en: "Hi! How are you?" },
      { sp: "سامر", ar: "منيح الحمد لله، وإنتِ كيفك؟", en: "Fine, thank God — and you, how are you?" },
      { sp: "ليلى", ar: "تمام. شو اسمك؟", en: "Great. What's your name?" },
      { sp: "سامر", ar: "اسمي سامر. وإنتِ؟", en: "My name is Samer. And you?" },
      { sp: "ليلى", ar: "أنا ليلى. من وين إنت؟", en: "I'm Layla. Where are you from?" },
      { sp: "سامر", ar: "أنا من عمان. وإنتِ من وين؟", en: "I'm from Amman. And where are you from?" },
      { sp: "ليلى", ar: "أنا من بيروت، بس ساكنة هون من سنتين.", en: "I'm from Beirut, but I've been living here for two years." },
      { sp: "سامر", ar: "حلو كتير! تشرفنا.", en: "Very nice! Pleased to meet you." },
      { sp: "ليلى", ar: "تشرفنا فيك.", en: "Pleased to meet you too." },
    ],
  },
  {
    id: "cafe",
    title: "At the café",
    titleAr: "بالقهوة",
    level: "A1",
    lines: [
      { sp: "الغرسون", ar: "أهلا وسهلا! شو بتحبوا تشربوا؟", en: "Welcome! What would you like to drink?" },
      { sp: "رنا", ar: "بدي قهوة لو سمحت.", en: "I'd like a coffee, please." },
      { sp: "الغرسون", ar: "سادة ولا مع سكر؟", en: "Black, or with sugar?" },
      { sp: "رنا", ar: "مظبوطة، لو سمحت.", en: "Medium-sweet, please." },
      { sp: "فادي", ar: "وأنا بدي شاي مع نعنع.", en: "And I'd like tea with mint." },
      { sp: "الغرسون", ar: "ماشي. في شي تاني؟", en: "Sure. Anything else?" },
      { sp: "فادي", ar: "قديش صحن الحمص؟", en: "How much is the plate of hummus?" },
      { sp: "الغرسون", ar: "بدينارين.", en: "Two dinars." },
      { sp: "فادي", ar: "طيب، جيبلنا صحن حمص كمان.", en: "OK, bring us a plate of hummus too." },
      { sp: "الغرسون", ar: "تكرم، دقيقة وبكون عندكم.", en: "Of course — one minute and I'll be right with you." },
    ],
  },
  {
    id: "market",
    title: "At the market",
    titleAr: "بالسوق",
    level: "A2",
    lines: [
      { sp: "الزبونة", ar: "مرحبا، قديش كيلو البندورة؟", en: "Hi, how much is a kilo of tomatoes?" },
      { sp: "البياع", ar: "أهلين، الكيلو بدينار.", en: "Hello — one dinar a kilo." },
      { sp: "الزبونة", ar: "غالي شوي! عندك أرخص؟", en: "A bit expensive! Do you have anything cheaper?" },
      { sp: "البياع", ar: "هاي بندورة بلدية يا ستي، أحلى شي بالسوق.", en: "These are local tomatoes, ma'am — the best in the market." },
      { sp: "الزبونة", ar: "طيب عطيني كيلوين، وكيلو خيار كمان.", en: "Fine, give me two kilos, and a kilo of cucumbers too." },
      { sp: "البياع", ar: "تكرمي. بدك شي تاني؟", en: "Of course. Do you want anything else?" },
      { sp: "الزبونة", ar: "لا خلص، هيك منيح. قديش صار المجموع؟", en: "No, that's it, this is fine. What does the total come to?" },
      { sp: "البياع", ar: "تلاتة ونص.", en: "Three and a half." },
      { sp: "الزبونة", ar: "تفضل. يعطيك العافية.", en: "Here you go. Thank you (may God give you strength)." },
      { sp: "البياع", ar: "الله يعافيكي.", en: "And you (the reply)." },
    ],
  },
  {
    id: "myday",
    title: "My day",
    titleAr: "يومي",
    level: "A2",
    lines: [
      { ar: "كل يوم بصحى الساعة سبعة الصبح.", en: "Every day I wake up at seven in the morning." },
      { ar: "بشرب قهوتي وباكل شي خفيف.", en: "I drink my coffee and eat something light." },
      { ar: "بعدين بروح عالشغل بالباص.", en: "Then I go to work by bus." },
      { ar: "الطريق بياخد شي نص ساعة.", en: "The trip takes about half an hour." },
      { ar: "بشتغل من الساعة تمانة لأربعة.", en: "I work from eight o'clock to four." },
      { ar: "بعد الشغل، أحياناً بلتقي مع صحابي.", en: "After work, sometimes I meet up with my friends." },
      { ar: "منقعد بمقهى ومنحكي عن كل شي.", en: "We sit in a café and talk about everything." },
      { ar: "بالليل برجع عالبيت تعبان بس مبسوط.", en: "At night I come back home tired but happy." },
    ],
  },
  {
    id: "phone",
    title: "On the phone",
    titleAr: "عالتلفون",
    level: "A2",
    lines: [
      { sp: "ريم", ar: "ألو؟ مرحبا نور!", en: "Hello? Hi Nour!" },
      { sp: "نور", ar: "أهلين ريم! كيفك؟ شو أخبارك؟", en: "Hey Reem! How are you? What's new?" },
      { sp: "ريم", ar: "تمام. شو رأيك نطلع بكرا؟", en: "Fine. What do you think about going out tomorrow?" },
      { sp: "نور", ar: "فكرة حلوة! وين بدك تروحي؟", en: "Nice idea! Where do you want to go?" },
      { sp: "ريم", ar: "في مطعم جديد جنب البحر، بقولوا أكله كتير طيب.", en: "There's a new restaurant by the sea — they say its food is really good." },
      { sp: "نور", ar: "ماشي، بس بكرا عندي شغل للساعة خمسة.", en: "OK, but tomorrow I have work until five o'clock." },
      { sp: "ريم", ar: "ولا يهمك، منروح الساعة سبعة.", en: "No worries, we'll go at seven." },
      { sp: "نور", ar: "عنجد ممتاز. بتحبي إجي آخدك بالسيارة؟", en: "Really great. Would you like me to come pick you up by car?" },
      { sp: "ريم", ar: "أكيد، بستناكي قدام البيت.", en: "Sure, I'll wait for you in front of the house." },
      { sp: "نور", ar: "اتفقنا! منشوفك بكرا.", en: "Deal! See you tomorrow." },
    ],
  },
  {
    id: "trip",
    title: "A trip to the mountains",
    titleAr: "مشوار عالجبل",
    level: "B1",
    lines: [
      { ar: "الجمعة الماضية، أنا وعيلتي طلعنا مشوار عالجبل.", en: "Last Friday, my family and I went on a trip to the mountains." },
      { ar: "صحينا بكير، حضّرنا الأكل، وركبنا بالسيارة.", en: "We woke up early, prepared the food, and got in the car." },
      { ar: "الطريق كان حلو كتير، والطقس ولا أحلى.", en: "The road was really beautiful, and the weather couldn't have been better." },
      { ar: "لما وصلنا، قعدنا تحت شجرة كبيرة وشربنا شاي.", en: "When we arrived, we sat under a big tree and drank tea." },
      { ar: "الولاد لعبوا وركضوا، ونحنا حكينا وضحكنا.", en: "The kids played and ran around, and we talked and laughed." },
      { ar: "عالضهر أكلنا مناقيش وسلطة وفواكه.", en: "At noon we ate manakish, salad, and fruit." },
      { ar: "قبل ما نرجع، أخدنا صور كتير للغروب.", en: "Before heading back, we took lots of photos of the sunset." },
      { ar: "رجعنا عالبيت بالليل تعبانين، بس كان يوم ما بينتسى.", en: "We got back home at night exhausted, but it was an unforgettable day." },
    ],
  },
];
